# Following:
# https://dev.to/epassaro/caching-anaconda-environments-in-github-actions-5hde
# https://github.com/epassaro/cache-conda-envs

name: test_install_dedalus3_conda
on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
jobs:
  build:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            label: linux-64
          - os: macos-latest
            label: osx-64
    name: ${{ matrix.label }}
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: Setup miniforge
        uses: conda-incubator/setup-miniconda@v2
        with:
          miniforge-version: latest
          auto-activate-base: true
          activate-environment: ""
      - name: Run conda installation
        run: bash install_dedalus3_conda.sh
      - name: Test conda installation
        run: |
          conda activate dedalus3
          python3 -m dedalus test
          
