
name: Test conda builds
on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
jobs:

  v2_from_conda_forge:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            label: linux-64
          - os: macos-latest
            label: osx-64
    name: v2 from conda-forge on ${{ matrix.label }}
    runs-on: ${{ matrix.os }}
    steps:
      - name: Setup miniforge
        uses: conda-incubator/setup-miniconda@v2
        with:
          miniforge-version: latest
          auto-activate-base: true
          activate-environment: ""
      - name: Build from conda-forge
        shell: bash -l {0}
        run: |
          conda create -y -n dedalus2
          conda activate dedalus2
          conda env config vars set OMP_NUM_THREADS=1
          conda env config vars set NUMEXPR_MAX_THREADS=1
          conda install -y -c conda-forge dedalus
      - name: Test build
        shell: bash -l {0}
        run: |
          conda activate dedalus2
          python3 -m dedalus test

  v2_master_via_conda_forge:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            label: linux-64
          - os: macos-latest
            label: osx-64
    name: v2-master via conda-forge on ${{ matrix.label }}
    runs-on: ${{ matrix.os }}
    steps:
      - name: Setup miniforge
        uses: conda-incubator/setup-miniconda@v2
        with:
          miniforge-version: latest
          auto-activate-base: true
          activate-environment: ""
      - name: Build from conda-forge
        shell: bash -l {0}
        run: |
          conda create -y -n dedalus2
          conda activate dedalus2
          conda env config vars set OMP_NUM_THREADS=1
          conda env config vars set NUMEXPR_MAX_THREADS=1
          conda install -y -c conda-forge dedalus c-compiler "h5py=*=mpi*"
          conda uninstall -y --force dedalus
          CC=mpicc pip3 install --no-cache http://github.com/dedalusproject/dedalus/zipball/v2_master/
      - name: Test build
        shell: bash -l {0}
        run: |
          conda activate dedalus2
          python3 -m dedalus test

  v3_master_via_conda_forge:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            label: linux-64
          - os: macos-latest
            label: osx-64
    name: v3-master via conda-forge on ${{ matrix.label }}
    runs-on: ${{ matrix.os }}
    steps:
      - name: Setup miniforge
        uses: conda-incubator/setup-miniconda@v2
        with:
          miniforge-version: latest
          auto-activate-base: true
          activate-environment: ""
      - name: Build from conda-forge
        shell: bash -l {0}
        run: |
          conda create -y -n dedalus3
          conda activate dedalus3
          conda env config vars set OMP_NUM_THREADS=1
          conda env config vars set NUMEXPR_MAX_THREADS=1
          conda install -y -c conda-forge dedalus c-compiler "h5py=*=mpi*"
          conda uninstall -y --force dedalus
          CC=mpicc pip3 install --no-cache http://github.com/dedalusproject/dedalus/zipball/master/
      - name: Test build
        shell: bash -l {0}
        run: |
          conda activate dedalus3
          python3 -m dedalus test

  v2_custom:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            label: linux-64
          - os: macos-latest
            label: osx-64
    name: v2 custom script on ${{ matrix.label }}
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup miniforge
        uses: conda-incubator/setup-miniconda@v2
        with:
          miniforge-version: latest
          auto-activate-base: true
          activate-environment: ""
      - name: Run conda installation
        shell: bash -l {0}
        run: bash conda_install_dedalus2.sh
      - name: Test conda installation
        shell: bash -l {0}
        run: |
          conda activate dedalus2
          python3 -m dedalus test

  v3_custom:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            label: linux-64
          - os: macos-latest
            label: osx-64
    name: v3 custom script on ${{ matrix.label }}
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup miniforge
        uses: conda-incubator/setup-miniconda@v2
        with:
          miniforge-version: latest
          auto-activate-base: true
          activate-environment: ""
      - name: Run conda installation
        shell: bash -l {0}
        run: bash conda_install_dedalus3.sh
      - name: Test conda installation
        shell: bash -l {0}
        run: |
          conda activate dedalus3
          python3 -m dedalus test
